name: Login

on: 
  push:
    branches: [master]

jobs:
  build: 
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: checkout 
        uses: actions/checkout@v4
        with:
            sparse-checkout: |
              .github
              src
      - name : setup python 
        uses: action/setup-python@v5
        with:
          python-version: '3.13'
      - name: Run Script
        run: python ./SeleniumTest/Tests/test_Base_Page.py   
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest  
          
      - name: commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: automated push
          commit_user_name: USBQ [git Actions]
          commit_user_email: buendiau@gmail.com
          commit_author: USBQ
        
  
    
